#!/usr/bin/env bash
# Guardrail checks for Tokade. Run by CI on every PR and by the pre-commit
# hook on every local commit. Each check enforces a rule from CLAUDE.md.
#
# Exits non-zero on the first violation. The error message tells you which
# rule was violated and where to look.

set -euo pipefail
cd "$(dirname "$0")/.."

fail() {
    echo "✗ $1" >&2
    exit 1
}

# Rule: never call Bundle.module directly. Use appBundledResource in
# SharedComponents.swift instead. (Reason: SPM's auto-generated accessor
# bakes the build-time path into the binary and crashes after a project
# rename or when run from /Applications.)
if grep -RIn --include='*.swift' "Bundle\.module" Sources/ \
        | grep -v "SharedComponents.swift" \
        | grep -v "^[[:space:]]*//"; then
    fail "Bundle.module used outside SharedComponents.swift. Use appBundledResource. See CLAUDE.md § Bundle lookups."
fi

# Rule: no network code. Tokade is offline by design.
if grep -RIn --include='*.swift' -E "URLSession|URLRequest|URLDownload|NSURLSession|NSURLRequest" Sources/ \
        | grep -v "^[[:space:]]*//"; then
    fail "Network primitive found in Sources/. Tokade is offline by design. See CLAUDE.md § No network."
fi

# Rule: stack-stability hacks in StatsView must stay in place. These exist
# because SwiftUI Charts will reshuffle colors and segment order on hover
# without them.
for marker in "chartForegroundStyleScale" "chartYScale(domain:" "sortedModels("; do
    if ! grep -q "$marker" Sources/Tokade/StatsView.swift; then
        fail "Missing stack-stability marker '$marker' in StatsView.swift. See CLAUDE.md § Chart stability."
    fi
done

# Rule: every Models.swift sequence extension that powers a chart has at
# least one corresponding test in Tests/TokadeTests/. We enforce by name
# matching on test methods.
for fn in groupedByModel groupedByProject toolCallCounts groupedBySlashCommand stackedByProjectAndModel; do
    if grep -q "func $fn" Sources/Tokade/Models.swift \
            && ! grep -RIqi "func test.*$fn" Tests/; then
        fail "Models.$fn has no test under Tests/. See CLAUDE.md § Critical-math test coverage."
    fi
done

# Rule: archives must set 0600 permissions on their data files. Enforces the
# privacy promise in the README.
for f in Sources/Tokade/EventArchive.swift Sources/Tokade/SnapshotArchive.swift; do
    if ! grep -q "0o600" "$f"; then
        fail "$f missing 0o600 permission assignment. See CLAUDE.md § Archive file permissions."
    fi
done

# Rule: Token Gaiden save file must also be 0600.
if [ -f Sources/Tokade/TokenGaiden/TokegotchiSave.swift ]; then
    if ! grep -q "0o600" Sources/Tokade/TokenGaiden/TokegotchiSave.swift; then
        fail "TokegotchiSave.swift missing 0o600 permission assignment. See CLAUDE.md § Token Gaiden state file permissions."
    fi
fi

# Rule: no LLM-attribution strings sneaking into committed code or comments.
# (Exclude this script itself, which has to mention the pattern to grep for it.)
if grep -RIn --include='*.swift' --include='*.md' \
        -iE "claude wrote|generated by claude|generated by an ai|gpt wrote" \
        Sources/ README.md 2>/dev/null \
        | grep -v "^[[:space:]]*<!--"; then
    fail "LLM-attribution string found. Remove before committing."
fi

echo "✓ All guardrail checks passed"
